<?php
namespace backend\controllers;

use backend\assets\DefaultAsset;
use Yii;

class Controller extends \yii\web\Controller
{
    public function beforeAction($action)
    {
        // 使用 default 主题
        Yii::$app->view->theme = Yii::createObject([
            'class' => 'yii\base\Theme',
            'basePath' => '@backend/themes/default',
            'baseUrl' => '@web/themes/default',
            'pathMap' => [
                '@backend/views' => '@backend/themes/default',
            ],
        ]);

        Yii::$app->view->params['defaultPath'] = Yii::$app->assetManager->getBundle(DefaultAsset::className())->baseUrl;

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }
}
